Repository ynput/ayon-substance-designer, pull requests merged in 2025-03, with the labels that each got.

#15 Support project creation by Task Type
  client/ayon_substancedesigner/api/project_creation.py
  client/ayon_substancedesigner/version.py
  package.py
  server/settings/main.py
Labels: type: enhancement, sponsored

#18 Chore: Revamp creator settings and stick to the built in settings applying
  client/ayon_substancedesigner/api/plugin.py
  client/ayon_substancedesigner/plugins/create/create_textures.py
  server/settings/main.py
Labels: type: enhancement

#16 UnloadUserPackage when loading new workfile
  client/ayon_substancedesigner/api/pipeline.py
Labels: type: enhancement

#20 Add dependencies during project creation
  client/ayon_substancedesigner/api/project_creation.py
Labels: type: bug, sponsored

#22 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature
